name: Serverless Config CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Buil and push the image
        run: |
          docker login --username ameen-91 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build . -t ghcr.io/ameen-91/serverless-config:latest
          docker push ghcr.io/ameen-91/serverless-config:latest